# CONTENIDO CORREGIDO:
title: "Writeups de HTB"
description: "Soluciones detalladas de máquinas HackTheBox"
theme: minima
baseurl: ""
css: /assets/css/style.css
url: "https://perovosolokoBite.github.io"
collections:
  writeups:
    output: true
    permalink: /writeups/:path/
